/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gg.sep.battlenet;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Tests for {@link Library}.
 */
class LibraryTest {
    @Test void testSomeLibraryMethod() {
        final Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
