/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gg.sep.battlenet;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import gg.sep.battlenet.Library;

class LibraryTest {
    @Test void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
